[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle SPA routing - important for direct links
[[redirects]]
  from = "/calculators"
  to = "/calculators.html"
  status = 200

[[redirects]]
  from = "/calculator1"
  to = "/calculator1.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"